//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysql.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirTransport
    {
        public int Id { get; set; }
        public string MenberId { get; set; }
        public int CustomId { get; set; }
        public string OrderNumber { get; set; }
        public string SourcePlace { get; set; }
        public string TargetPlace { get; set; }
        public string Tag { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
