//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysql.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirTransportDetails
    {
        public int Id { get; set; }
        public Nullable<int> AirTransportId { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
    }
}
